routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('justas', 'HomeController@justas');

Route::get('/', 'DishController@index');

Auth::routes();

Route::resource('dishes', 'DishController');

Route::resource('orders', 'OrderController');
Route::delete('orders/line/{id}/destroy', 'OrderController@destroyLine')->name('orders.line_destroy');
Route::put('order/{id}/add-dish', 'OrderController@addToOrder')->name('order.add_dish');

Route::resource('tables', 'TableController');
Route::resource('users',  'UserController');

//cart route
Route::post('cart', 'OrderController@addToCart')->name('cart.add');
Route::delete('cart', 'OrderController@clearCart')->name('cart.clear');
Route::get('cart', 'OrderController@checkout')->name('cart.checkout');
Route::get('cart/delete/{id}', 'OrderController@deleteLine')->name('cart.delete_line');
Route::get('cart/reservation', 'CheckoutController@info')->name('checkout.info');
Route::post('cart/reservation', 'CheckoutController@store')->name('checkout.store');
Route::get('cart/confirm', 'CheckoutController@confirm')->name('checkout.confirm');

// user routes
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');

// contact page
Route::get('contact', 'ContactController@show')->name('contact.show');
Route::get('contact/edit', 'ContactController@edit')->name('contact.edit');
Route::put('contact', 'ContactController@update')->name('contact.update');

app/Dish.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dish extends Model
{
    protected $fillable =[
    	'title',
    	'photo',
    	'description',
    	'netto_price',
    	'price',
    	'quantity'
    ];
    public function getFormattedPriceAttribute($value)
    {
       return number_format($this->price / 100, 2);
    }
    public function getFormattedNetoPriceAttribute($value)
    {
       return number_format($this->netto_price / 100, 2);
    }
    public function order_lines()
   {
     return $this->hasMany('App\OrderLine');
   }

   public function getWithoutVat()
   {
       return \App\Price::getWithoutVat($this->FormattedPrice);
   }

   public function getVat()
   {
       return $this->FormattedPrice - $this->getWithoutVat();
   }
}

app/Http/Controllers/DishController.php
<?php

namespace App\Http\Controllers;

use App\Dish;
use Illuminate\Http\Request;

class DishController extends Controller
{
    public function __construct() {
        $this->middleware('auth.admin')
             ->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dishes = Dish::all();
        return view('dish.index', compact('dishes')); /**['dishes'=> $dishes] tas pats butu compact($dishes)*/
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('dish.form', compact('dish'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->hasFile('photo')){
            $file = $request->file('photo');
            $file->store('public');
            $photo= $file->hashName();
            }

       Dish::create([
            'title' => $request->get('title'),
            'photo' => $request->photo,
            'description' => $request->get('description'),
            'price' => $request->get('price'),
            'netto_price' => $request->get('netto_price'),
            'quantity' => $request->get('quantity'),
          ]);


        return redirect()->route('dishes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Dish  $dish
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dish = Dish::find($id);
        return view('dish.show', compact('dish'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Dish  $dish
     * @return \Illuminate\Http\Response
     */
    public function edit(Dish $dish)
    {
        return view('dish.form', compact('dish'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Dish  $dish
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Dish $dish)
    {
           if ($request->hasFile('photo')){
            $file = $request->file('photo');
            $file->store('public');
            $request->photo= $file->hashName();
            }

           $dish->title= $request->title;
           $dish->description = $request->description;
           $dish->price = $request->price;
           $dish->netto_price = $request->netto_price;
           $dish->quantity = $request->quantity;
           $dish->photo = $request->photo;

           $dish->update();

        return redirect()->route('dishes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Dish  $dish
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Dish::find($id)->delete();
        return redirect()->route('dishes.index');

    }
}

resources/views/dish/form.blade.php
@extends('layouts.app')


	@section('content')
		
		<h2>Tik pabandyk pakeisti...!</h2>

		@if(isset($dish))
			{!! Form::model($dish, [
			'route' => ['dishes.update', $dish->id],
			'method' => 'put',
			'files' => true
			]) !!}
		@else
			{!! Form::open(['route' => 'dishes.store', 'method' => 'post', 'files' => true]) !!}
		@endif
			
			<div class="from-group">    
			{!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title'])!!}
			</div>
			
			<div class="from-group">  
			{!! Form::textarea('description', null, ['class' => 'form-control', 'placeholder' => 'Description']) !!}
			</div>
			
			
			
						
			<div class="from-group">  
			{!! Form::number('price', null, ['class' => 'form-control', 'placeholder' => 'Price']) !!}
			</div>
			<div class="from-group">  
			{!! Form::number('netto_price', null, ['class' => 'form-control', 'placeholder' => 'Netto Price']) !!}
			</div>
			
			<div class="from-group">  
			{!! Form::number('quantity', null, ['class' => 'form-control', 'placeholder' => 'Quantity']) !!}
			</div>

			<div class="from-group">  
			{!! Form::file('photo', null, ['class' => 'form-control', 'placeholder' => 'IMAGE']) !!}

			</div>
	@if (Auth::check()) 

			{!! Form::submit('Save' ,['class' => 'btn-primary']) !!}
	
		@endif 	

		{!! Form::close() !!}



		@if(isset($dish))
			{!! Form::open(['route' => ['dishes.destroy', $dish->id], 'method' => 'delete'])!!}
				{!! Form::submit('Delete' , ['class' => 'btn btn-danger'])!!}
			{!! Form::close() !!}
		@endif

@endsection

resources/views/dish/index.blade.php
@extends('layouts.app')

@section('content')

<h2>MUSU patiekalai</h2>

@if(Auth::user() && Auth::user()->isAdmin())
<a href="{{route('dishes.create') }}" class="btn btn-primary" role="button">Sukurti nauja</a> 
@endif		

@foreach ($dishes->chunk(4) as $chunk) 
<div class="row">
	@foreach ($chunk as $dish)
	<div class="col-md-3"> {{ $dish->title }}
		<div class="thumbnail">
			<img class="img-responsive" src="{{ $dish->photo }}" >

			<div class="caption">
				<h3> {{ $dish->title }} </h3>
				<p> {{ $dish->description }} </p>
				<p>
					<strong>KAINA:</strong>
					{{ $dish->FormattedPrice }} 
					<strong>KAINA:</strong>
					{{ $dish->FormattedNetoPrice }}
					<strong>EUR</strong>
					<br>
					<strong>KIEKIS:</strong>
					{{ $dish->quantity }} 
					<strong>vnt.</strong>
				</p>
				<p>
					<a href="{{route('dishes.show', $dish->id) }}" class="btn btn-primary" role="button">PERZIURETI</a>
					<a href="#" class="btn btn-warning add-to-cart"  data-id="{{ $dish->id }}" role="button">Add to cart</a>  
				</p>
			</div>			
		</div>
	</div>
	@endforeach	
</div>
@endforeach	
@endsection

resources/views/dish/show.blade.php
@extends('layouts.app')

	@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<h2>{{ $dish->title }}</h2>
				<div style="background-image: url({{ $dish->photo }}); height:300px; background-position:center;  background-size: cover;"></div>
				
				<p>{{ $dish->description }}</p>
				<ul>
					<li>{{ $dish->Formattedprice }}<strong> EUR</strong></li>
					<li>{{ $dish->quantity }}<strong> vnt.</strong></li>
				</ul>


			@if (Auth::check()) 
	   		 <a href="{{route('dishes.edit', $dish->id) }}" class="btn btn-primary">EDIT</a>
			@endif 

		</div>

	</div>

	</div>

		
	@endsection