routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('justas', 'HomeController@justas');

Route::get('/', 'DishController@index');

Auth::routes();

Route::resource('dishes', 'DishController');

Route::resource('orders', 'OrderController');
Route::delete('orders/line/{id}/destroy', 'OrderController@destroyLine')->name('orders.line_destroy');
Route::put('order/{id}/add-dish', 'OrderController@addToOrder')->name('order.add_dish');

Route::resource('tables', 'TableController');
Route::resource('users',  'UserController');

//cart route
Route::post('cart', 'OrderController@addToCart')->name('cart.add');
Route::delete('cart', 'OrderController@clearCart')->name('cart.clear');
Route::get('cart', 'OrderController@checkout')->name('cart.checkout');
Route::get('cart/delete/{id}', 'OrderController@deleteLine')->name('cart.delete_line');
Route::get('cart/reservation', 'CheckoutController@info')->name('checkout.info');
Route::post('cart/reservation', 'CheckoutController@store')->name('checkout.store');
Route::get('cart/confirm', 'CheckoutController@confirm')->name('checkout.confirm');

// user routes
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');

// contact page
Route::get('contact', 'ContactController@show')->name('contact.show');
Route::get('contact/edit', 'ContactController@edit')->name('contact.edit');
Route::put('contact', 'ContactController@update')->name('contact.update');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Order extends Model
{
    protected $fillable =[
    	'name',
    	'email',
    	'total',
    	'date',
    	'user_id',
        'reservation_date',
        'reservation_time',
        'table_id',
        'number_of_persons'
   ];

   public function order_lines()
   {
   	 return $this->hasMany('App\OrderLine');
   }
   public function user()
   {
   	return $this->belongsTo('App\User');
   }

   public function table()
   {
       return $this->belongsTo('App\Table');
   }

   public function getReservationClass()
   {
       /* šviesaforą rodome tik tada, kai žiūri administratorius */
       if (\Auth::check() && \Auth::user()->isAdmin()) {
           $date = Carbon::parse($this->reservation_date);

           if ($date->isToday()) {
               return 'danger';
           } else if ($date->isTomorrow()) {
               return 'info';
           } else if ($date->isPast()) {
               return 'success';
           }
       }

       return '';
   }

   public function getWithoutVat()
   {
       return \App\Price::getWithoutVat($this->total);
   }

   public function getVat()
   {
       return $this->total - $this->getWithoutVat();
   }

   public function recalculate()
   {
       $this->total = 0;
       foreach ($this->order_lines()->get() as $line) {
           $this->total += $line->total;
       }
   }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Dish;
use App\Order;
use App\OrderLine;
use App\Table;
use Illuminate\Http\Request;
use App\Price;

class OrderController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth.admin')
             ->except(['index', 'store', 'show', 'addToCart', 'clearCart', 'deleteLine', 'checkout']);

        $this->middleware('auth')
             ->except(['addToCart', 'clearCart', 'deleteLine', 'checkout']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (\Auth::user()->isAdmin()) {
            $orders = Order::orderBy('date', 'desc')->get();
        } else {
            $orders = \Auth::user()->orders()->orderBy('date', 'desc')->get();
        }

       return view('order.index', ['orders'=> $orders]);
    }
//


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       if (session('cart.total')){
        return view('order.form');
       } else {
        return redirect()->route('dishes.index');
       }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order = Order::create([
            'name' => session('cart.reservation_info.name'),
            'email' => 'aurimas.baubkus@gmail.com',
            'total' => session('cart.total'),
            'date' => \Carbon\Carbon::now(),
            'user_id' => \Auth::user()->id,
            'reservation_date' => '2017-03-22',
            'reservation_time' => '20:00',
            'number_of_persons' => 2,
            'table_id' => session('cart.reservation_info.table_id')
        ]);

        foreach(session('cart.items') as $item) {
            OrderLine::create([
                'order_id' => $order->id,
                'dish_id' => $item['id'],
                'quantity' => $item['quantity'],
                'total' => $item['total']
            ]);
        }
        $this-> clearCart();
        return redirect()->route('orders.index')->with('message', [
                'text' => 'Užsakymas sėkmingai pateiktas!',
                'type' => 'success'
            ]
            );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);
        return view('order.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::find($id);
        $dishes = Dish::all()->pluck('title', 'id');
        return view('order.form', compact('order', 'dishes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [

           'name' => 'required|max:255',
           'tables' => 'required|exists:tables,id',
           'email' => 'required|email|max:255',
           'reservation_date' => 'nullable|date|date_format:Y-m-d',
           'contact_phone' => 'required|numeric',
           'number_of_persons' => 'required|numeric|between:0,15',
           'reservation_time' => 'required',

        ]);

        Order::find($id)->update($request->all());


        return redirect()->route('orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */


    public function destroy(Order $order, Request $request)
    {
        $order->order_lines()->delete();
        $order->delete();

        if ($request->has('redirect_url')) {
            return redirect()->to($request->redirect_url);
        }

        return redirect()->route('orders.index');
    }

    public function addToCart(Request $request){
        // session(['cart.items'=> [] ]);
        $dish_id = $request->id;

        $dish = Dish::find($dish_id);
        $product = [
            'id' => $dish->id,
            'photo' => $dish->photo,
            'title' => $dish->title,
            'quantity' => 1,
            'price' => $dish->FormattedPrice,
            'total' =>$dish->FormattedPrice,
            'without_vat' => $dish->getWithoutVat(),
            'vat' => $dish->getVat()
        ];
            $items = session('cart.items');
            $existing = false;
            $grand_total = 0;

        if ($items && count($items) > 0) {

            foreach($items as $index => $item) {
                if($item['id'] == $dish_id) {
                    $items[$index]['quantity'] = $item['quantity'] + $product['quantity'];
                    $items[$index]['total'] = $items[$index]['quantity'] * $dish->FormattedPrice;

                    $items[$index]['without_vat'] = $items[$index]['quantity'] * $dish->getWithoutVat();
                    $items[$index]['vat'] = $items[$index]['quantity'] * $dish->getVat();

                    $existing = true;
                    $grand_total = $grand_total + $items[$index]['total'];
                } else{
                    $grand_total = $grand_total + $item['total'];
                }

                }
            }

           if(! $existing){
                session()->push('cart.items', $product);
                $grand_total += $product['total'];
            } else {
                session(['cart.items'=> $items]);
            }

            $withoutVat = Price::getWithoutVat($grand_total);
            $vat = Price::getVat($grand_total);

            session([
                'cart.total_without_vat' => $withoutVat,
                'cart.total_vat' => $vat,
                'cart.total' => $grand_total
            ]);

            return session('cart');
    }

    public function clearCart() {
        session(['cart.items' => [], 'cart.total' =>0]);
    }

    public function deleteLine(Request $request)
    {
        $id = $request->id;
        $items = session('cart.items');

        $total = session('cart.total');

        foreach ($items as $index => $item) {
            if ($item['id'] == $id) {
                $total -= $item['total'];
                unset($items[$index]);
                break;
            }
        }

        session([
            'cart.items' => $items,
            'cart.total' => $total
        ]);

        return redirect()->route('cart.checkout');
    }


    public function checkout()
    {
        return view('order.checkout');
    }

    public function destroyLine($id)
    {
        $line = OrderLine::findOrFail($id);
        $line->delete();

        $order = Order::find($line->order->id);
        $order->recalculate();
        $order->save();

        return redirect()->route('orders.edit', $line->order->id)->with('message', [
            'type' => 'info',
            'text' => 'dish removed'
        ]);
    }

    public function addToOrder($id, Request $request)
    {
        $order = Order::findOrFail($id);
        $collection = OrderLine::where([
            'dish_id' => $request->dish,
            'order_id' => $order->id
        ])->get();

        $dish = Dish::findOrFail($request->dish);

        if ($collection->count() > 0) {
            $line = $collection->first();

        } else {
            $line = new \App\OrderLine();
            $line->order_id = $order->id;
            $line->dish_id = $dish->id;
        }

        $line->quantity += $request->quantity;
        $line->total = $dish->price * $line->quantity;
        $line->save();

        $order->recalculate();
        $order->save();

        return redirect()->route('orders.edit', $order->id)->with('message', [
            'text' => 'Dish added!',
            'type' => 'success'
        ]);
    }
 }

resources/views/order/checkout.blade.php
@extends('layouts.app')

@section('content')

<div class="table-responsive">
  <table class="table">

	<tbody>
		<thead>
			<th>Pavadinimas</th>
			<th>Kiekis</th>
			<th>Vnt. Kaina</th>
            <th>PVM</th>
            <th>Viso be PVM</th>
			<th>Viso</th>
			<th></th>
		</thead>
	@if(session('cart.items') && count(session('cart.items'))>0)
        @foreach(session('cart.items') as $item)
            <tr>
                <td>{{ $item['title']}} <img src="{{$item['photo']}}" alt="{{ $item['title']}}" class="img-rounded" style="width: 70px;"> </td>
                <td>{{ $item['quantity']}} vnt.</td>
                <td>{{ $item['price']}}€</td>
                <td>{{ $item['vat'] }}€</td>
                <td>{{ $item['without_vat'] }}€</td>
                <td>{{ $item['total']}} &euro;</td>
               <td><a class="clear-line-cart" href="{{ route('cart.delete_line', ['id' => $item['id']] ) }}"><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
             </tr>

            @endforeach
            <tfoot>
            	<td></td>
            	<td></td>
            	<td>Viso: </td>
                <td>{{ session('cart.total_vat') ?: '0' }} €</td>
            	<td>{{ session('cart.total_without_vat') ?: '0' }} &euro;</td>
            	<td> {{session('cart.total') ?: '0'}} &euro;</td>
            </tfoot>
        @endif

	</tbody>

  </table>

   <a href="{{route('checkout.info') }}" class="btn btn-success">Continue</a>
</div>







@endsection

resources/views/order/form.blade.php
@extends('layouts.app')


	@section('content')

		<h2>Iveskite uzsakyma rankutemis, jei laukai yra tusti...!</h2>

		@if (count($errors) > 0)
		    <div class="alert alert-danger">
		        <ul>
		            @foreach ($errors->all() as $error)
		                <li>{{ $error }}</li>
		            @endforeach
		        </ul>
		    </div>
		@endif

		@if(isset($order))
			{!! Form::model($order, [
			'route' => ['orders.update', $order->id], 'method' => 'put'
			]) !!}
		@else
			{!! Form::open(['route' => 'orders.store', 'method' => 'post']) !!}
		@endif

			<div class="from-group">
			{!! Form::text('name', Auth::user() ? Auth::user()->name: null, ['class' => 'form-control', 'placeholder' => 'Name'])!!}
			</div>
			<div class="from-group">
			{!! Form::text('email', Auth::user() ? Auth::user()->email: null, ['class' => 'form-control', 'placeholder' => 'Email'])!!}
			</div>
		@if(session('cart.total'))
		<p> Suma: {{session('cart.total') }} &euro;</p>
		@else
			<div class="from-group">
			{!! Form::number('total', null, ['class' => 'form-control', 'placeholder' => 'Total']) !!}
			</div>
		@endif

		@if (Auth::check())
			{!! Form::submit('Save' ,['class' => 'btn-primary']) !!}
			{!! Form::close() !!}
		@endif

		@if (count($order->order_lines))
			<table class="table">
				<tr>
					<th>Dish</th>
					<th>Quantity</th>
					<th>Price</th>
					<th></th>
				</tr>
			@foreach ($order->order_lines as $line)
				<tr>
					<td>{{ $line->dish->title }}</td>
					<td>{{ $line->quantity }}</td>
					<td>{{ $line->total }} &euro;</td>
					<td>
						{!! Form::open(['route' => ['orders.line_destroy', $line->id], 'method' => 'delete'])!!}
							{!! Form::submit('Delete' , ['class' => 'btn btn-danger'])!!}
						{!! Form::close() !!}
					</td>
				</tr>
			@endforeach
			</table>
		@endif

		{!! Form::open(['route' => ['order.add_dish', $order->id], 'method' => 'put']) !!}
			{!! Form::number('quantity', null, ['class' => 'form-control', 'placeholder' => 'Quantity']) !!}
			{!! Form::select('dish', $dishes, ['class' => 'form-control', 'placeholder' => 'Select dish']) !!}
			{!! Form::submit('Add Dish', ['class' => 'btn btn-primary']) !!}
		{!! Form::close() !!}

		@if(isset($order))
			{!! Form::open(['route' => ['orders.destroy', $order->id], 'method' => 'delete'])!!}
				{!! Form::submit('Delete' , ['class' => 'btn btn-danger'])!!}
			{!! Form::close() !!}
		@endif

@endsection

resources/views/order/index.blade.php
@extends('layouts.app')

@section('content')

<h2>Užsakymų sąrašas:</h2>

		<hr>
			<div class="row">
				@foreach ($orders as $order)
					<div class="col-md-6 col-md-offset-3">
						<ul>
							<li>
								<h4>Vardas: {{ $order->name }} </h4>
								<p>el.paštas: {{ $order->email }} </p>
								<p>
									PVM {{ $order->getVat() }} € <br />
									Suma be PVM: {{ $order->getWithoutVat() }} €<br />
									Užsakymo suma:{{ $order->total }} €
								</p>
								<p>Užsakymo data: {{ $order->date }}
							<p><a href="{{route('orders.show', $order->id) }}" class="btn btn-primary" role="button">Perziurėti</a></p>

							</li>
							<hr>
						</ul>



					</div>
		 		@endforeach

			</div>
 		<hr>
 		<a href="{{route('orders.create') }}" class="btn btn-primary" role="button">Sukurti nauja</a>
@endsection

resources/views/order/show.blade.php
@extends('layouts.app')

	@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<ul>
					<li>{{ $order->name }} </li>
					<li>{{ $order->email }} </li>
					<li>{{ $order->total }} </li>
					<li>{{ $order->date }} </li>
					@if (Auth::check()) 
	   		 <a href="{{route('orders.edit', $order->id) }}" class="btn btn-primary">Redaguoti</a>
			@endif 
				</ul>
				<table class="table">
						<thead>
							<th>Pavadinimas</th>
							<th>Kiekis</th>
							<th>Kaina</th>
							<th>Viso</th>
							<th>Siuksline</th>
						</thead>
					@if(count($order->order_lines()) >0)
				       <tbody>
				        @foreach($order->order_lines as $item) 
				            <tr>         
				                <td>{{ $item->dish->title }} <img src="{{$item->dish->photo}}" alt="{{ $item->dish->title }}" class="img-rounded" style="width: 70px;"> </td>
				                <td>{{ $item->quantity }} </td>
				                <td>{{ $item->dish->price }} </td>
				                <td>{{ $item->total }} </td>
				                <td><a id="clear-line-cart" href="#" ><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
				            </tr>  
				        @endforeach
				        </tbody>
				        <tfoot>
			            	<tr>
			            		<td colspan="3" class="text-right">Total:</td>
			            		<td>{{ $order->total }}</td>
			            	</tr>
				        </tfoot>  
				    @endif
				</table>
   				<a href="{{route('orders.create') }}" class="btn btn-success">PIRKTI</a>
			</div>
		</div>
	</div>
	@endsection